site_name: The PHP SERP Scraper
pages:
  - Home: index.md
  - Getting Started:
    - Overview: overview.md
    - Http Client: http-client.md
    - Proxies: proxies.md
    - Captcha: captcha.md
  - Search Engine:
    - Google:
      - Google Client: search-engine/google.md
      - Search Parameters: search-engine/google/parameters.md
      - Parse a Page: search-engine/google/parse-page.md

  - Http Clients:
      - CURL: http-client/curl.md
      - PhantomJS: http-client/phantomJS.md




repo_url: https://github.com/serp-scrape/serps

site_description: >
  SERPS is a SERP Scraper for php.
  It offers a set of tools to manipulate and parse popular search engines such as Google, Yahoo, Bing...

site_favicon: null

google_analytics: null


extra_css:
  - css/serps.css