site_name: The PHP SERP Scraper

pages:
  - Documentation:
    - Home: index.md
    - Overview: overview.md
    - Http Client: http-client.md
    - Proxies: proxies.md
    - Captcha: captcha.md

  - Search Engines:
    - Google:
      - Google Client: search-engine/google.md
      - Search Parameters: search-engine/google/parameters.md
      - Parse a Page: search-engine/google/parse-page.md

  - Http Clients:
      - CURL: http-client/curl.md
      - PhantomJS: http-client/phantomJS.md

  - Contribute:
    - Guidelines: contribute/guidelines.md
    - Packages: contribute/packages.md
    - Implement Http Client: contribute/http-client-implementation.md

repo_url: https://github.com/serp-scrape/serps

site_description: >
  SERPS is a SERP Scraper for php.
  It offers a set of tools to manipulate and parse popular search engines such as Google, Yahoo, Bing...

site_favicon: null

google_analytics: null

extra_css:
  - css/serps.css