site_name: SERPS Documentation

pages:
  - Documentation:
    - About SERPS: index.md
    - Overview: overview.md
    - Cookies: cookies.md

  - Search Engines:
    - Google:
      - Google Client: search-engine/google.md
      - Parse a Page: search-engine/google/parse-page.md

  - Http Clients:
      - CURL: http-client/curl.md
      - PhantomJS: http-client/phantomJS.md

  - Contribute:
    - Packages: contribute/packages.md

repo_url: https://github.com/serp-scrape/serps

theme_dir: 'themes/serps'

site_description: >
  SERPS is a SERP Scraper for php.
  It offers a set of tools to manipulate and parse popular search engines such as Google, Yahoo, Bing...

site_favicon: favicon.ico

google_analytics:
  - UA-75620778-1
  - serp-scrape.github.io

extra_css:
  - css/serps.css


markdown_extensions:
  - admonition